### ISSUE TITLE
Server monitoring check option is useless and generates a lot of traffic

### ISSUE THREAD

**Issue by jfhampton** [trick77/tunlr-style-dns-unblocking#28]
Hi

First of all, thanks for your work !

After starting haproxy, I monitored tcp connections with tcpdump and saw a lot of traffic going to the differrent proxied servers.
The haproxy configuration uses "check" option to check the status of each server every 10 seconds, that means that the VPS is continuously opening outgoing connections to proxied servers.
This check method is useful when haproxy is used as a reverse proxy to balance traffic within a server farm. In our case, haproxy is only a proxy to the internet and we are not in charge of balancing the traffic, that job is done by netflix and other companies.

So, in order to keep activity as low as possible on the VPS and to stay under the radar, the server_options parameter found in config.json should be empty ("server_options": ""). I use this configuration without any problem to proxy netflix.com domains.

**Comment by trick77** [comment]
It does not generate a "lot of traffic". It's just a L4 syn/ack and does not show up on L7 logs on the destination server anyway.
